name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db"
database_id = "c4cffed9-636a-446a-8f2b-f360b697f236"

[version_metadata]
binding = "CF_VERSION_METADATA"
